package com.example.csrf.controller;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * Exposes the current CSRF token to the frontend (EARS-001).
 *
 * The token is generated by PerRequestCsrfFilter and stored as a request attribute
 * before this controller method executes.  The frontend calls GET /api/csrf on page
 * load to seed its client-side token cache.
 */
@RestController
@RequestMapping("/api")
public class CsrfController {

    @GetMapping("/csrf")
    public Map<String, String> getCsrfToken(HttpServletRequest request) {
        String token = (String) request.getAttribute("_csrf_token");
        return Map.of("token", token != null ? token : "");
    }
}
